# Default values for microservices-demo
# This is a YAML-formatted file.
replicaCount: 1
frontend:
  name: frontend
  image:
    repository: ghcr.io/wahaj4311/3-tier-app/frontend
    tag: "c5ae286d"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
serviceA:
  name: service-a
  image:
    repository: ghcr.io/wahaj4311/3-tier-app/service-a
    tag: "c5ae286d"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3001
    targetPort: 3001
serviceB:
  name: service-b
  image:
    repository: ghcr.io/wahaj4311/3-tier-app/service-b
    tag: "c5ae286d"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3002
    targetPort: 3002
database:
  name: postgres
  image:
    repository: postgres
    tag: 13
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  storage:
    size: 1Gi
# Canary deployment settings
canary:
  enabled: false
  percentage: 20
ingressNginx:
  enabled: true
  controller:
    service:
      externalTrafficPolicy: Local
# Azure Key Vault configuration
keyVault:
  enabled: false # Set to true when using Azure Key Vault
  name: "" # Name of the Key Vault
  tenantId: "" # Azure Tenant ID
  secrets:
    - name: postgres-db-secret
      keys:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
# Database configuration
db:
  # These values should be overridden in production using --set or a values file
  user: "CHANGE_ME"
  password: "CHANGE_ME"
  name: "CHANGE_ME"
  host: "postgres-service"
  port: 5432
# Secret configuration
secrets:
  # These values should be overridden in production using --set or a values file
  dbUser: "CHANGE_ME"
  dbPassword: "CHANGE_ME"
  dbName: "CHANGE_ME"
