apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/kubemicrodemo.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-prod
  syncPolicy:
    # Manual sync for production
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true 