{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "aks-gitops-cluster-kv"
    objects: |
      array:
        - |
          objectName: db-username
          objectType: secret
          objectAlias: DB_USERNAME
        - |
          objectName: db-password
          objectType: secret
          objectAlias: DB_PASSWORD
    tenantId: "${TENANT_ID}"  # Will be replaced during deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  annotations:
    secrets-store.csi.k8s.io/managed: "true"
type: Opaque
data:
  username: ""  # Will be populated by CSI driver
  password: ""  # Will be populated by CSI driver
{{- end }} 