{{- if not .Values.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
{{- end }} 