{{- if not .Values.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.dbUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.dbName | b64enc | quote }}
{{- end }} 