apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc # Name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gibibyte of storage
  # storageClassName: standard # Optional: Specify a StorageClass if needed, depends on your K8s cluster setup
