apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Replace these with base64 encoded values of your actual credentials
  POSTGRES_USER: BASE64_ENCODED_USER
  POSTGRES_PASSWORD: BASE64_ENCODED_PASSWORD
  POSTGRES_DB: BASE64_ENCODED_DBNAME 