apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Base64 encoded values: user=dXNlcg==, password=cGFzc3dvcmQ=, dbname=bWljcm9zZXJ2aWNlX2Ri
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: bWljcm9zZXJ2aWNlX2Ri
