apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
spec:
  replicas: 2 # Example: run 2 replicas
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        # Using the locally built image in Minikube
        image: service-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002 # Port the service listens on
        # Add readiness and liveness probes (optional but recommended)
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3002
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3002
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
spec:
  selector:
    app: service-b # Select Pods with the 'app: service-b' label
  ports:
    - protocol: TCP
      port: 3002 # Port the Service listens on
      targetPort: 3002 # Port on the Pods to forward traffic to
  type: ClusterIP # Expose internally
