apiVersion: v1
kind: Namespace
metadata:
  name: csi-secrets-store
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: key-vault-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    chart: csi-secrets-store-provider-azure
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    targetRevision: 1.4.0
    helm:
      values: |
        linux:
          enabled: true
        windows:
          enabled: false
        syncSecret:
          enabled: true
        enableSecretRotation: true
        podAnnotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-secrets-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m