apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "aks-gitops-cluster-kv"  # This should match your Key Vault name created by Terraform
    objects: |
      array:
        - |
          objectName: db-username
          objectType: secret
          objectAlias: DB_USERNAME
        - |
          objectName: db-password
          objectType: secret
          objectAlias: DB_PASSWORD
    tenantId: "${TENANT_ID}"  # This will be replaced by the GitHub workflow 
  secretObjects:
  - secretName: postgres-db-secret
    type: Opaque
    data:
    - objectName: DB_USERNAME
      key: POSTGRES_USER
    - objectName: DB_PASSWORD
      key: POSTGRES_PASSWORD 