name: Terraform Infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy infrastructure'
        required: true
        default: 'dev'
        type: choice
        options: [dev, prod]
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options: [plan, apply, destroy]

env:
  ENVIRONMENT: ${{ inputs.environment || (github.ref == 'refs/heads/main' && 'prod' || 'dev') }}
  TF_ACTION: ${{ inputs.action || 'plan' }}

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      storage_account: ${{ steps.bootstrap.outputs.storage_account_name }}
      container_name: ${{ steps.bootstrap.outputs.container_name }}
      resource_group: ${{ steps.bootstrap.outputs.resource_group_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Bootstrap Backend Storage
        id: bootstrap
        run: |
          cd terraform/bootstrap
          terraform init
          terraform apply -auto-approve \
            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          
          # Save outputs to files first
          terraform output -raw storage_account_name > storage_account.txt
          terraform output -raw container_name > container.txt
          terraform output -raw resource_group_name > resource_group.txt
          
          # Read from files and set outputs
          echo "storage_account_name=$(cat storage_account.txt)" >> $GITHUB_OUTPUT
          echo "container_name=$(cat container.txt)" >> $GITHUB_OUTPUT
          echo "resource_group_name=$(cat resource_group.txt)" >> $GITHUB_OUTPUT
          
          # Print confirmation
          echo "Successfully created backend infrastructure:"
          echo "Storage Account: $(cat storage_account.txt)"
          echo "Container: $(cat container.txt)"
          echo "Resource Group: $(cat resource_group.txt)"

  terraform:
    needs: bootstrap
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init \
            -backend-config="resource_group_name=${{ needs.bootstrap.outputs.resource_group }}" \
            -backend-config="storage_account_name=${{ needs.bootstrap.outputs.storage_account }}" \
            -backend-config="container_name=${{ needs.bootstrap.outputs.container_name }}" \
            -backend-config="key=terraform-${{ env.ENVIRONMENT }}.tfstate" \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -out=tfplan

      - name: Terraform Apply
        if: env.TF_ACTION == 'apply' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main')
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: env.TF_ACTION == 'destroy' && github.event_name == 'workflow_dispatch'
        run: |
          cd terraform
          terraform destroy -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="db_username=${{ secrets.DB_USERNAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Export Terraform Outputs
        if: env.TF_ACTION == 'apply' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main')
        id: terraform-outputs
        run: |
          cd terraform
          # Store key outputs as GitHub outputs
          echo "AKS_CLUSTER_NAME=$(terraform output -raw kubernetes_cluster_name)" >> $GITHUB_OUTPUT
          echo "AKS_RESOURCE_GROUP=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT 